### ISSUE TITLE
Problem with symbol '>' and '<'

### ISSUE THREAD

**Issue by mroliveira7** [yohasebe/rsyntaxtree#2]
Hello, Yohasebe. 
First of all, thanks for this amazing tool.
But I found a little problem with the checking and generating the leaves with symbol '>' and '<'

When i try this : 
[binop [T_NAME i][T_LT <][T_NUMBER 3]]

it keeps saying "Expression is not valid" but just changing '>' for anything else it works again.

**Comment by yohasebe** [comment]
Sorry for my belated response. I made a quick fix to it. Now you can include '>' (and '<') in the input text.
