### ISSUE TITLE
RubyNLP

### ISSUE THREAD

**Issue by arbox** [yohasebe/rsyntaxtree#3]
Dear Yoichiro,

I've recently added your project to our RubyNLP list: https://github.com/arbox/nlp-with-ruby

I wonder if you want to participate in the Ruby for NLP network. You could do this in a very simple step by adding the `rubynlp` topic to your GitHub repository. You may want to spread a word on Twitter or on other media :)

Thank you for the project!

**Comment by yohasebe** [comment]
Hi Andrei,

Thanks for letting me know about your RubyNLP project. I added `rubynlp` topic to some of my repositories including `engtagger`

https://github.com/yohasebe/engtagger

which you may find worth including in your list.

Thanks!

**Comment by arbox** [comment]
Thank you! Actually you may want to add every project worth it yourself :) The list is open for contributions!
