### ISSUE TITLE
Dependency tree

### ISSUE THREAD

**Issue by arjunmenon** [yohasebe/rsyntaxtree#4]
Hey
Is there any ruby program to generate the dependency tree in the first place?

I would not prefer to use stanfords, it is very bloated and slow. Part of the reason sticking with `engtagger`. Much faster and equally efficient.

Anything like that for dependency parsing?

**Comment by yohasebe** [comment]
I can't think of any good dependency parser written in pure ruby. Actually I use [Enju](http://www.nactem.ac.uk/enju/) for syntactic parsing. It's a C program, if I understand it correctly. There is no existing ruby interface, so you need to write code to pipe command line outputs. Enju is a bit old and not extremely fast, but at least it compiles to a single file binary.
