### ISSUE TITLE
Support Movement Trace

### ISSUE THREAD

**Issue by jiahao-c** [yohasebe/rsyntaxtree#6]
Hello. Could you support movement curve drawing?  Thanks.
Like these:
![image](https://user-images.githubusercontent.com/8275280/71911200-4a746a00-3141-11ea-9309-f60d959e53ad.png)
![image](https://user-images.githubusercontent.com/8275280/71911211-506a4b00-3141-11ea-8268-21a75f2c75fb.png)

**Comment by yohasebe** [comment]
I'm sorry for not being able to respond to your request. In the current version, you can draw an ovation trace. Give it a try. Thank you!
