### ISSUE TITLE
Allow %

### ISSUE THREAD

**Issue by dorianim** [yohasebe/rsyntaxtree#7]
Please allow the `%` sign. I am not able to use it, even when escaping.
Otherwise it's a nice tool!

**Comment by yohasebe** [comment]
I made a quick fix for this. Try it out either commandline or online. Escape is unnecessary. Thanks for your kind words!

**Comment by yohasebe** [comment]
I found that the problem rendering the % symbol was a little more complex than I had first regarded it. Just for a workaround, RSyntaxTree 1.0.4 replaces "%" with "％", a full-width variant of the same symbol.

**Comment by yohasebe** [comment]
Fixed (1.0.5)!

**Comment by dorianim** [comment]
Thanks! That fixed it :)
