### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by jregio** [yohasebe/rsyntaxtree#8]
Hi Yohasebe, thank you for making this tool!  I am trying to use the command-line tool on Google Colab and I am running into some issues.  When I run the help option, I get the expected results.  But if I try to input a string I get the following error:

![Test](https://user-images.githubusercontent.com/98362199/196842391-6a09d307-9458-458c-8aa6-930750911ef3.PNG)

And I get a different error with the following:

![Test test](https://user-images.githubusercontent.com/98362199/196842426-a959c12b-ad17-47f6-a11b-02268a65abf8.PNG)

If it helps, here is how I installed rsyntaxtree on Google Colab:
```
!sudo apt update
!sudo apt upgrade
!apt-get install ruby-dev
!sudo apt install libtool libffi-dev ruby ruby-dev make
!sudo apt install libzmq3-dev libczmq-dev
!gem install ffi-rzmq
!sudo apt-get install -y libmagickcore-dev
!sudo gem install rake
!sudo gem install rainbow -v '2.2.2'
!sudo gem install rsyntaxtree
```

Thanks!

**Comment by yohasebe** [comment]
This is a very tentative attempt, but here is how you can install RSyntaxTree in Google Colaboratory:

```
!apt update && apt upgrade
!apt install -y build-essential libssl-dev zlib1g-dev
!apt install -y imagemagick imagemagick-common libmagickcore-dev libmagickwand-dev
!git clone https://github.com/rbenv/rbenv.git /root/.rbenv
!git clone https://github.com/rbenv/ruby-build.git /root/.rbenv/plugins/ruby-build
!/root/.rbenv/bin/rbenv install 3.1.2
!/root/.rbenv/bin/rbenv global 3.1.2

import os
os.environ['PATH'] = '/root/.rbenv/versions/3.1.2/bin:' + os.environ['PATH']

!gem install rsyntaxtree
```
Then you can use RSyntaxTree.

```
!rsyntaxtree "[S [NP RSyntaxTree] [VP [V generates] [NP [Adj multilingual] [NP syntax trees] ] ] ]"
```

The resulting image will be saved as `syntree.png`

**Comment by jregio** [comment]
This worked like magic, thank you!
