### ISSUE TITLE
Color (enhancement)

### ISSUE THREAD

**Issue by Swerup** [yohasebe/rsyntaxtree#9]
I wish there was a way to add color to the items, for example:
[RED{RED}GREEN{GREEN}
    ^ black text (on COLOR:NONE mode)
]
the text "REDGREEN" in color red and green, then color a daughter node  black
{COLOR} nodes could color everything in current node form it forward until it reached another {COLOR} node (above code)

or they could color everything in current node after it that color until it reached another {COLOR} node.(below code)
[{RED}RED{GREEN}GREEN
    ^ black text (on COLOR:NONE mode)
]

**Comment by yohasebe** [comment]
I'm sorry for not getting back to you sooner! I appreciate your idea of using color tags to specify the desired colors for text and nodes. However, I am not inclined to introduce coloring syntax to rsyntaxtree for the following reasons:

- Adding new tags for coloring could make the rsyntaxtree notation even more complicated. It's important to maintain the notation's simplicity and ease of use.
- Coloring tree elements is already possible by outputting the image as SVG and editing it with software like Inkscape or Illustrator. This approach can achieve the desired result without adding complexity to the notation.

I hope you understand my perspective on this matter. If you have any further questions or concerns, please feel free to let me know.

**Comment by Swerup** [comment]
Oh i see! no worries!
